[providers]
php = "8.3"
node = "20"

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.gd", "php83Extensions.zip", "nodejs_20"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build"
]
